### GET request to example server
POST http://localhost:8080/v1/organization/optima/license
Content-Type: application/json

{
  "organizationName": "optima",
  "description": "Software product",
  "organizationId": "optima",
  "productName": "Ostock",
  "licenseType": "full"
}
###
###
GET http://localhost:8080/v1/organization/optima/license/27a4f8f8-3e3b-4aba-8529-336602706ab7/discovery
###

###
PUT http://localhost:8080/v1/organization/optima/license
Content-Type: application/json

{
  "licenseId": "lic-1001",
  "description": "Software product",
  "organizationId": "123",
  "productName": "Ostock",
  "licenseType": "full"
}

###
DELETE http://localhost:8080/v1/organization/optima/license/1
###

###
GET http://localhost:8070/eureka/apps
###

###
PUT http://localhost:8081/v1/organization/optima
Content-Type: application/json

{
  "name": "Optima",
  "contactName": "Ivan",
  "contactEmail": "ivan@optima.test",
  "contactPhone": "+7-000"
}
###

###
GET http://localhost:8081/v1/organization/optima
Content-Type: application/json

###