spring.application.name=microservice
spring.profiles.active=dev
spring.config.import=optional:configserver:http://localhost:8071
management.endpoints.web.exposure.include=refresh
example.property=I AM THE DEFAULT

spring.datasource.url=jdbc:postgresql://localhost:5432/licenses
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true